logging:
    file:
        name: logs/ch08.log
    level:
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /sboard
spring:
    application:
        name: sboard
        version: ${version}
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@16.184.40.180:1522/XEPDB1
        username: tndus159200297
        password: 1234
    devtools:
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

    security:
      user:
        name: user
        password: 1234
        roles: ADMIN
